### ISSUE TITLE
Getting API key

### ISSUE THREAD

**Issue by eteitelbaum** [econabhishek/datagovindia#1]
Thanks for developing this! I am wondering if you know whether it is possible for people based outside of India to get an API key for the OGD platform. When I try using my GitHub or LinkedIn ID the website takes me to sign up for Meri Pehchaan, which I am not sure non-nationals can even sign up for. In any case, when I enter my US phone no. to generate an OTP I don't receive any message as a result. 

I know this is not an issue with your package, just wondering if you know. Thanks!

**Comment by econabhishek** [comment]
Hi @eteitelbaum  - thanks for engaging with the package! 
I am afraid that I don't know any method to bypass this - my only recommendation would be to ask someone you know who has an Indian number for an API key. 


Abhishek
